version: "3.7"
services:
  cypress:
    image: cypress/included:3.2.0
    networks: ['botfront-network']
    volumes:
    - ./botfront:/e2e
    - ./wait-for-it.sh:/e2e/wait-for-it.sh
    working_dir: /e2e
    entrypoint: ./wait-for-it.sh
    depends_on:
    - botfront
    environment:
    - CYPRESS_IS_CI=true
    - CYPRESS_baseUrl=http://botfront:3000

  botfront:
    image: botfront/botfront
    restart: always
    networks: ['botfront-network']
    ports:
    - "8888:3000"
    depends_on:
    - mongoimage
    environment:
      - PORT=3000
      - ROOT_URL=http://localhost:8888
      - MONGO_URL=mongodb://mongoimage:27017/bf
      - METEOR_PROFILE=1
      - METEOR_LOG=debug
      - ORCHESTRATOR=docker-compose

  mongoimage:
    image: mongo
    restart: always
    networks: ["botfront-network"]
    volumes:
    - ./db:/data/db
    # ports:
    # - "27017:27017"
    environment: 
      MONGO_INITDB_DATABASE: bf

networks: 
  botfront-network: {}
volumes:
  db: